# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-01 06:16
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CheckVoucher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner', models.TextField()),
                ('particulars', models.TextField()),
                ('supplier', models.TextField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('cvno', models.TextField()),
                ('amount', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Snippet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('code', models.CharField(blank=True, default=b'', max_length=100)),
                ('project', models.CharField(choices=[(b'Project', b'Project')], default=b'python', max_length=100)),
                ('materials', models.CharField(blank=True, default=b'', max_length=100)),
                ('CR', models.TextField()),
                ('DR', models.TextField()),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snippets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('created',),
            },
        ),
    ]
